/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PostnlShippingClient) {
      root.PostnlShippingClient = {};
    }
    root.PostnlShippingClient.Content = factory(root.PostnlShippingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Content model module.
   * @module model/Content
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Content</code>.
   * @alias module:model/Content
   * @class
   * @param description {String} Description of goods
   * @param quantity {String} Quantity of items in description
   * @param weight {String} Net weight of goods in gram(gr)
   * @param value {String} Commercial (customs) value of goods.
   */
  var exports = function(description, quantity, weight, value) {
    var _this = this;

    _this['Description'] = description;


    _this['Quantity'] = quantity;
    _this['Weight'] = weight;
    _this['Value'] = value;


  };

  /**
   * Constructs a <code>Content</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Content} obj Optional instance to populate.
   * @return {module:model/Content} The populated <code>Content</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('EAN')) {
        obj['EAN'] = ApiClient.convertToType(data['EAN'], 'String');
      }
      if (data.hasOwnProperty('ProductURL')) {
        obj['ProductURL'] = ApiClient.convertToType(data['ProductURL'], 'String');
      }
      if (data.hasOwnProperty('Quantity')) {
        obj['Quantity'] = ApiClient.convertToType(data['Quantity'], 'String');
      }
      if (data.hasOwnProperty('Weight')) {
        obj['Weight'] = ApiClient.convertToType(data['Weight'], 'String');
      }
      if (data.hasOwnProperty('Value')) {
        obj['Value'] = ApiClient.convertToType(data['Value'], 'String');
      }
      if (data.hasOwnProperty('HSTariffNr')) {
        obj['HSTariffNr'] = ApiClient.convertToType(data['HSTariffNr'], 'String');
      }
      if (data.hasOwnProperty('CountryOfOrigin')) {
        obj['CountryOfOrigin'] = ApiClient.convertToType(data['CountryOfOrigin'], 'String');
      }
    }
    return obj;
  }

  /**
   * Description of goods
   * @member {String} Description
   * @default 'Powdered milk'
   */
  exports.prototype['Description'] = 'Powdered milk';
  /**
   * A unique code for a product. Together with HS number this is mandatory for product code 4992.
   * @member {String} EAN
   */
  exports.prototype['EAN'] = undefined;
  /**
   * Webshop URL of the product which is being shipped. Mandatory for product code 4992
   * @member {String} ProductURL
   */
  exports.prototype['ProductURL'] = undefined;
  /**
   * Quantity of items in description
   * @member {String} Quantity
   * @default '2'
   */
  exports.prototype['Quantity'] = '2';
  /**
   * Net weight of goods in gram(gr)
   * @member {String} Weight
   * @default '2600'
   */
  exports.prototype['Weight'] = '2600';
  /**
   * Commercial (customs) value of goods.
   * @member {String} Value
   * @default '20.00'
   */
  exports.prototype['Value'] = '20.00';
  /**
   * First 6 numbers of Harmonized System Code
   * @member {String} HSTariffNr
   * @default '100878'
   */
  exports.prototype['HSTariffNr'] = '100878';
  /**
   * Origin country code
   * @member {String} CountryOfOrigin
   * @default 'NL'
   */
  exports.prototype['CountryOfOrigin'] = 'NL';



  return exports;
}));


