/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Content'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Content'));
  } else {
    // Browser globals (root is window)
    if (!root.PostnlShippingClient) {
      root.PostnlShippingClient = {};
    }
    root.PostnlShippingClient.Customs = factory(root.PostnlShippingClient.ApiClient, root.PostnlShippingClient.Content);
  }
}(this, function(ApiClient, Content) {
  'use strict';




  /**
   * The Customs model module.
   * @module model/Customs
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Customs</code>.
   * The Customs type is mandatory for GlobalPack shipments and not allowed for any other shipment types.
   * @alias module:model/Customs
   * @class
   * @param currency {String} Currency code,only EUR and USS are allowed
   * @param content {Array.<module:model/Content>} 
   */
  var exports = function(currency, content) {
    var _this = this;








    _this['Currency'] = currency;

    _this['Content'] = content;
  };

  /**
   * Constructs a <code>Customs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Customs} obj Optional instance to populate.
   * @return {module:model/Customs} The populated <code>Customs</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Certificate')) {
        obj['Certificate'] = ApiClient.convertToType(data['Certificate'], 'Boolean');
      }
      if (data.hasOwnProperty('CertificateNr')) {
        obj['CertificateNr'] = ApiClient.convertToType(data['CertificateNr'], 'String');
      }
      if (data.hasOwnProperty('License')) {
        obj['License'] = ApiClient.convertToType(data['License'], 'Boolean');
      }
      if (data.hasOwnProperty('LicenseNr')) {
        obj['LicenseNr'] = ApiClient.convertToType(data['LicenseNr'], 'String');
      }
      if (data.hasOwnProperty('Invoice')) {
        obj['Invoice'] = ApiClient.convertToType(data['Invoice'], 'Boolean');
      }
      if (data.hasOwnProperty('InvoiceNr')) {
        obj['InvoiceNr'] = ApiClient.convertToType(data['InvoiceNr'], 'String');
      }
      if (data.hasOwnProperty('HandleAsNonDeliverable')) {
        obj['HandleAsNonDeliverable'] = ApiClient.convertToType(data['HandleAsNonDeliverable'], 'Boolean');
      }
      if (data.hasOwnProperty('Currency')) {
        obj['Currency'] = ApiClient.convertToType(data['Currency'], 'String');
      }
      if (data.hasOwnProperty('ShipmentType')) {
        obj['ShipmentType'] = ApiClient.convertToType(data['ShipmentType'], 'String');
      }
      if (data.hasOwnProperty('Content')) {
        obj['Content'] = ApiClient.convertToType(data['Content'], [Content]);
      }
    }
    return obj;
  }

  /**
   * At least one of the three types Certificate, Invoice or License is mandatory for Commercial Goods,Commercial Sample and Returned Goods
   * @member {Boolean} Certificate
   */
  exports.prototype['Certificate'] = undefined;
  /**
   * Mandatory when Certificate is true. 
   * @member {String} CertificateNr
   */
  exports.prototype['CertificateNr'] = undefined;
  /**
   * At least one of the three types Certificate, Invoice or License is mandatory for Commercial Goods,Commercial Sample and Returned Goods
   * @member {Boolean} License
   */
  exports.prototype['License'] = undefined;
  /**
   * Mandatory when License is true.
   * @member {String} LicenseNr
   */
  exports.prototype['LicenseNr'] = undefined;
  /**
   * At least one of the three types Certificate, Invoice or License is mandatory for Commercial Goods,Commercial Sample and Returned Goods
   * @member {Boolean} Invoice
   * @default true
   */
  exports.prototype['Invoice'] = true;
  /**
   * Mandatory when Invoice is true
   * @member {String} InvoiceNr
   * @default 'INV_0120330'
   */
  exports.prototype['InvoiceNr'] = 'INV_0120330';
  /**
   * Determines what to do when the shipment cannot be delivered the first time (if this is set to true,the shipment will be returned after the first failed attempt)
   * @member {Boolean} HandleAsNonDeliverable
   */
  exports.prototype['HandleAsNonDeliverable'] = undefined;
  /**
   * Currency code,only EUR and USS are allowed
   * @member {String} Currency
   * @default 'EUR'
   */
  exports.prototype['Currency'] = 'EUR';
  /**
   * Type of shipment,possible values: Gift,Documents,Commercial Goods,Commercial Sample,Returned Goods
   * @member {String} ShipmentType
   * @default 'Commercial Goods'
   */
  exports.prototype['ShipmentType'] = 'Commercial Goods';
  /**
   * @member {Array.<module:model/Content>} Content
   */
  exports.prototype['Content'] = undefined;



  return exports;
}));


