/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Address'));
  } else {
    // Browser globals (root is window)
    if (!root.PostnlShippingClient) {
      root.PostnlShippingClient = {};
    }
    root.PostnlShippingClient.Customer = factory(root.PostnlShippingClient.ApiClient, root.PostnlShippingClient.Address);
  }
}(this, function(ApiClient, Address) {
  'use strict';




  /**
   * The Customer model module.
   * @module model/Customer
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Customer</code>.
   * @alias module:model/Customer
   * @class
   * @param collectionLocation {String} Code of delivery location at PostNL Pakketten
   * @param customerCode {String} Customer code as known at PostNL Pakketten
   * @param customerNumber {String} Name of customer contact person
   */
  var exports = function(collectionLocation, customerCode, customerNumber) {
    var _this = this;


    _this['CollectionLocation'] = collectionLocation;

    _this['CustomerCode'] = customerCode;
    _this['CustomerNumber'] = customerNumber;


  };

  /**
   * Constructs a <code>Customer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Customer} obj Optional instance to populate.
   * @return {module:model/Customer} The populated <code>Customer</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Address')) {
        obj['Address'] = Address.constructFromObject(data['Address']);
      }
      if (data.hasOwnProperty('CollectionLocation')) {
        obj['CollectionLocation'] = ApiClient.convertToType(data['CollectionLocation'], 'String');
      }
      if (data.hasOwnProperty('ContactPerson')) {
        obj['ContactPerson'] = ApiClient.convertToType(data['ContactPerson'], 'String');
      }
      if (data.hasOwnProperty('CustomerCode')) {
        obj['CustomerCode'] = ApiClient.convertToType(data['CustomerCode'], 'String');
      }
      if (data.hasOwnProperty('CustomerNumber')) {
        obj['CustomerNumber'] = ApiClient.convertToType(data['CustomerNumber'], 'String');
      }
      if (data.hasOwnProperty('Email')) {
        obj['Email'] = ApiClient.convertToType(data['Email'], 'String');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Address} Address
   */
  exports.prototype['Address'] = undefined;
  /**
   * Code of delivery location at PostNL Pakketten
   * @member {String} CollectionLocation
   * @default '1234506'
   */
  exports.prototype['CollectionLocation'] = '1234506';
  /**
   * Name of customer contact person
   * @member {String} ContactPerson
   * @default 'Janssen'
   */
  exports.prototype['ContactPerson'] = 'Janssen';
  /**
   * Customer code as known at PostNL Pakketten
   * @member {String} CustomerCode
   * @default 'DEVC'
   */
  exports.prototype['CustomerCode'] = 'DEVC';
  /**
   * Name of customer contact person
   * @member {String} CustomerNumber
   * @default '11223344'
   */
  exports.prototype['CustomerNumber'] = '11223344';
  /**
   * E-mail address of the customer 
   * @member {String} Email
   * @default 'email@company.com'
   */
  exports.prototype['Email'] = 'email@company.com';
  /**
   * Customer name
   * @member {String} Name
   * @default 'Janssen'
   */
  exports.prototype['Name'] = 'Janssen';



  return exports;
}));


