/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Customer', 'model/Message', 'model/Shipments'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Customer'), require('./Message'), require('./Shipments'));
  } else {
    // Browser globals (root is window)
    if (!root.PostnlShippingClient) {
      root.PostnlShippingClient = {};
    }
    root.PostnlShippingClient.GenerateLabel = factory(root.PostnlShippingClient.ApiClient, root.PostnlShippingClient.Customer, root.PostnlShippingClient.Message, root.PostnlShippingClient.Shipments);
  }
}(this, function(ApiClient, Customer, Message, Shipments) {
  'use strict';




  /**
   * The GenerateLabel model module.
   * @module model/GenerateLabel
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>GenerateLabel</code>.
   * @alias module:model/GenerateLabel
   * @class
   * @param customer {module:model/Customer} 
   * @param message {module:model/Message} 
   * @param shipments {module:model/Shipments} 
   */
  var exports = function(customer, message, shipments) {
    var _this = this;

    _this['Customer'] = customer;

    _this['Message'] = message;
    _this['Shipments'] = shipments;
  };

  /**
   * Constructs a <code>GenerateLabel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GenerateLabel} obj Optional instance to populate.
   * @return {module:model/GenerateLabel} The populated <code>GenerateLabel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Customer')) {
        obj['Customer'] = Customer.constructFromObject(data['Customer']);
      }
      if (data.hasOwnProperty('LabelSignature')) {
        obj['LabelSignature'] = ApiClient.convertToType(data['LabelSignature'], 'String');
      }
      if (data.hasOwnProperty('Message')) {
        obj['Message'] = Message.constructFromObject(data['Message']);
      }
      if (data.hasOwnProperty('Shipments')) {
        obj['Shipments'] = Shipments.constructFromObject(data['Shipments']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/Customer} Customer
   */
  exports.prototype['Customer'] = undefined;
  /**
   * GIF image of the signature (as a base64 encoded string). The value of this element can have a maximum size of 65536 characters. Note that the total request can have a maximum size of 200KB. Larger requests will not be accepted by the server for performance reasons. Requests that exceed this limit will not return a validation error,but a HTTP 404 error.
   * @member {String} LabelSignature
   */
  exports.prototype['LabelSignature'] = undefined;
  /**
   * @member {module:model/Message} Message
   */
  exports.prototype['Message'] = undefined;
  /**
   * @member {module:model/Shipments} Shipments
   */
  exports.prototype['Shipments'] = undefined;



  return exports;
}));


