/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PostnlShippingClient) {
      root.PostnlShippingClient = {};
    }
    root.PostnlShippingClient.Group = factory(root.PostnlShippingClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Group model module.
   * @module model/Group
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Group</code>.
   * @alias module:model/Group
   * @class
   * @param groupType {String} Group sort that determines the type of group that is indicated. This is a code. Possible values: 01 = Collection request 03 = Multiple parcels in one shipment (multicolli) 04 = Single parcel in one shipment
   * @param groupSequence {String} Sequence number of the collo within the complete shipment (e.g. collo 2 of 4) Mandatory for multicollo shipments
   * @param groupCount {String} Total number of colli in the shipment (in case of multicolli shipments) Mandatory for multicollo shipments
   * @param mainBarcode {String} Main barcode for the shipment (in case of multicolli shipments) Mandatory for multicollo shipments
   */
  var exports = function(groupType, groupSequence, groupCount, mainBarcode) {
    var _this = this;

    _this['GroupType'] = groupType;
    _this['GroupSequence'] = groupSequence;
    _this['GroupCount'] = groupCount;
    _this['MainBarcode'] = mainBarcode;
  };

  /**
   * Constructs a <code>Group</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Group} obj Optional instance to populate.
   * @return {module:model/Group} The populated <code>Group</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('GroupType')) {
        obj['GroupType'] = ApiClient.convertToType(data['GroupType'], 'String');
      }
      if (data.hasOwnProperty('GroupSequence')) {
        obj['GroupSequence'] = ApiClient.convertToType(data['GroupSequence'], 'String');
      }
      if (data.hasOwnProperty('GroupCount')) {
        obj['GroupCount'] = ApiClient.convertToType(data['GroupCount'], 'String');
      }
      if (data.hasOwnProperty('MainBarcode')) {
        obj['MainBarcode'] = ApiClient.convertToType(data['MainBarcode'], 'String');
      }
    }
    return obj;
  }

  /**
   * Group sort that determines the type of group that is indicated. This is a code. Possible values: 01 = Collection request 03 = Multiple parcels in one shipment (multicolli) 04 = Single parcel in one shipment
   * @member {String} GroupType
   * @default '04'
   */
  exports.prototype['GroupType'] = '04';
  /**
   * Sequence number of the collo within the complete shipment (e.g. collo 2 of 4) Mandatory for multicollo shipments
   * @member {String} GroupSequence
   * @default '1'
   */
  exports.prototype['GroupSequence'] = '1';
  /**
   * Total number of colli in the shipment (in case of multicolli shipments) Mandatory for multicollo shipments
   * @member {String} GroupCount
   * @default '1'
   */
  exports.prototype['GroupCount'] = '1';
  /**
   * Main barcode for the shipment (in case of multicolli shipments) Mandatory for multicollo shipments
   * @member {String} MainBarcode
   * @default '3SABCD7239264'
   */
  exports.prototype['MainBarcode'] = '3SABCD7239264';



  return exports;
}));


