/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ResponseLabels', 'model/ResponseWarnings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ResponseLabels'), require('./ResponseWarnings'));
  } else {
    // Browser globals (root is window)
    if (!root.PostnlShippingClient) {
      root.PostnlShippingClient = {};
    }
    root.PostnlShippingClient.ResponseMergedLabels = factory(root.PostnlShippingClient.ApiClient, root.PostnlShippingClient.ResponseLabels, root.PostnlShippingClient.ResponseWarnings);
  }
}(this, function(ApiClient, ResponseLabels, ResponseWarnings) {
  'use strict';




  /**
   * The ResponseMergedLabels model module.
   * @module model/ResponseMergedLabels
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ResponseMergedLabels</code>.
   * @alias module:model/ResponseMergedLabels
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ResponseMergedLabels</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseMergedLabels} obj Optional instance to populate.
   * @return {module:model/ResponseMergedLabels} The populated <code>ResponseMergedLabels</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ProductCodeDelivery')) {
        obj['ProductCodeDelivery'] = ApiClient.convertToType(data['ProductCodeDelivery'], 'Number');
      }
      if (data.hasOwnProperty('Labels')) {
        obj['Labels'] = ApiClient.convertToType(data['Labels'], [ResponseLabels]);
      }
      if (data.hasOwnProperty('Warnings')) {
        obj['Warnings'] = ApiClient.convertToType(data['Warnings'], [ResponseWarnings]);
      }
      if (data.hasOwnProperty('Barcodes')) {
        obj['Barcodes'] = ApiClient.convertToType(data['Barcodes'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} ProductCodeDelivery
   */
  exports.prototype['ProductCodeDelivery'] = undefined;
  /**
   * @member {Array.<module:model/ResponseLabels>} Labels
   */
  exports.prototype['Labels'] = undefined;
  /**
   * @member {Array.<module:model/ResponseWarnings>} Warnings
   */
  exports.prototype['Warnings'] = undefined;
  /**
   * @member {Array.<String>} Barcodes
   */
  exports.prototype['Barcodes'] = undefined;



  return exports;
}));


