/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PostnlShippingClient);
  }
}(this, function(expect, PostnlShippingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PostnlShippingClient.Address();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Address', function() {
    it('should create an instance of Address', function() {
      // uncomment below and update the code to test Address
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be.a(PostnlShippingClient.Address);
    });

    it('should have the property addressType (base name: "AddressType")', function() {
      // uncomment below and update the code to test the property addressType
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property area (base name: "Area")', function() {
      // uncomment below and update the code to test the property area
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property buildingname (base name: "Buildingname")', function() {
      // uncomment below and update the code to test the property buildingname
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "City")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "CompanyName")', function() {
      // uncomment below and update the code to test the property companyName
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property countrycode (base name: "Countrycode")', function() {
      // uncomment below and update the code to test the property countrycode
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property department (base name: "Department")', function() {
      // uncomment below and update the code to test the property department
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property doorcode (base name: "Doorcode")', function() {
      // uncomment below and update the code to test the property doorcode
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "FirstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property floor (base name: "Floor")', function() {
      // uncomment below and update the code to test the property floor
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property houseNr (base name: "HouseNr")', function() {
      // uncomment below and update the code to test the property houseNr
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property houseNrExt (base name: "HouseNrExt")', function() {
      // uncomment below and update the code to test the property houseNrExt
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "Name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property region (base name: "Region")', function() {
      // uncomment below and update the code to test the property region
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "Street")', function() {
      // uncomment below and update the code to test the property street
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property streetHouseNrExt (base name: "StreetHouseNrExt")', function() {
      // uncomment below and update the code to test the property streetHouseNrExt
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

    it('should have the property zipcode (base name: "Zipcode")', function() {
      // uncomment below and update the code to test the property zipcode
      //var instane = new PostnlShippingClient.Address();
      //expect(instance).to.be();
    });

  });

}));
