/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PostnlShippingClient);
  }
}(this, function(expect, PostnlShippingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PostnlShippingClient.Contact();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Contact', function() {
    it('should create an instance of Contact', function() {
      // uncomment below and update the code to test Contact
      //var instane = new PostnlShippingClient.Contact();
      //expect(instance).to.be.a(PostnlShippingClient.Contact);
    });

    it('should have the property contactType (base name: "ContactType")', function() {
      // uncomment below and update the code to test the property contactType
      //var instane = new PostnlShippingClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "Email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new PostnlShippingClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property sMSNr (base name: "SMSNr")', function() {
      // uncomment below and update the code to test the property sMSNr
      //var instane = new PostnlShippingClient.Contact();
      //expect(instance).to.be();
    });

    it('should have the property telNr (base name: "TelNr")', function() {
      // uncomment below and update the code to test the property telNr
      //var instane = new PostnlShippingClient.Contact();
      //expect(instance).to.be();
    });

  });

}));
