/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PostnlShippingClient);
  }
}(this, function(expect, PostnlShippingClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PostnlShippingClient.Customs();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Customs', function() {
    it('should create an instance of Customs', function() {
      // uncomment below and update the code to test Customs
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be.a(PostnlShippingClient.Customs);
    });

    it('should have the property certificate (base name: "Certificate")', function() {
      // uncomment below and update the code to test the property certificate
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property certificateNr (base name: "CertificateNr")', function() {
      // uncomment below and update the code to test the property certificateNr
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property license (base name: "License")', function() {
      // uncomment below and update the code to test the property license
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property licenseNr (base name: "LicenseNr")', function() {
      // uncomment below and update the code to test the property licenseNr
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property invoice (base name: "Invoice")', function() {
      // uncomment below and update the code to test the property invoice
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNr (base name: "InvoiceNr")', function() {
      // uncomment below and update the code to test the property invoiceNr
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property handleAsNonDeliverable (base name: "HandleAsNonDeliverable")', function() {
      // uncomment below and update the code to test the property handleAsNonDeliverable
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "Currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property shipmentType (base name: "ShipmentType")', function() {
      // uncomment below and update the code to test the property shipmentType
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "Content")', function() {
      // uncomment below and update the code to test the property content
      //var instane = new PostnlShippingClient.Customs();
      //expect(instance).to.be();
    });

  });

}));
