/**
 * Postnl shipping client
 * A NodeJS API client for PostNL shipping services. Features include Generating barcdes, Generating labels in Base64
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Address', 'model/Amount', 'model/Contact', 'model/Content', 'model/Customer', 'model/Customs', 'model/Dimension', 'model/Error', 'model/GenerateLabel', 'model/Group', 'model/Message', 'model/ProductOption', 'model/Response', 'model/ResponseLabels', 'model/ResponseMergedLabels', 'model/ResponseResponseShipments', 'model/ResponseWarnings', 'model/Shipments', 'api/DefaultApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Address'), require('./model/Amount'), require('./model/Contact'), require('./model/Content'), require('./model/Customer'), require('./model/Customs'), require('./model/Dimension'), require('./model/Error'), require('./model/GenerateLabel'), require('./model/Group'), require('./model/Message'), require('./model/ProductOption'), require('./model/Response'), require('./model/ResponseLabels'), require('./model/ResponseMergedLabels'), require('./model/ResponseResponseShipments'), require('./model/ResponseWarnings'), require('./model/Shipments'), require('./api/DefaultApi'));
  }
}(function(ApiClient, Address, Amount, Contact, Content, Customer, Customs, Dimension, Error, GenerateLabel, Group, Message, ProductOption, Response, ResponseLabels, ResponseMergedLabels, ResponseResponseShipments, ResponseWarnings, Shipments, DefaultApi) {
  'use strict';

  /**
   * A_NodeJS_API_client_for_PostNL_shipping_services__Features_include_Generating_barcdes_Generating_labels_in_Base64.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var PostnlShippingClient = require('index'); // See note below*.
   * var xxxSvc = new PostnlShippingClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new PostnlShippingClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new PostnlShippingClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new PostnlShippingClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address: Address,
    /**
     * The Amount model constructor.
     * @property {module:model/Amount}
     */
    Amount: Amount,
    /**
     * The Contact model constructor.
     * @property {module:model/Contact}
     */
    Contact: Contact,
    /**
     * The Content model constructor.
     * @property {module:model/Content}
     */
    Content: Content,
    /**
     * The Customer model constructor.
     * @property {module:model/Customer}
     */
    Customer: Customer,
    /**
     * The Customs model constructor.
     * @property {module:model/Customs}
     */
    Customs: Customs,
    /**
     * The Dimension model constructor.
     * @property {module:model/Dimension}
     */
    Dimension: Dimension,
    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error: Error,
    /**
     * The GenerateLabel model constructor.
     * @property {module:model/GenerateLabel}
     */
    GenerateLabel: GenerateLabel,
    /**
     * The Group model constructor.
     * @property {module:model/Group}
     */
    Group: Group,
    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message: Message,
    /**
     * The ProductOption model constructor.
     * @property {module:model/ProductOption}
     */
    ProductOption: ProductOption,
    /**
     * The Response model constructor.
     * @property {module:model/Response}
     */
    Response: Response,
    /**
     * The ResponseLabels model constructor.
     * @property {module:model/ResponseLabels}
     */
    ResponseLabels: ResponseLabels,
    /**
     * The ResponseMergedLabels model constructor.
     * @property {module:model/ResponseMergedLabels}
     */
    ResponseMergedLabels: ResponseMergedLabels,
    /**
     * The ResponseResponseShipments model constructor.
     * @property {module:model/ResponseResponseShipments}
     */
    ResponseResponseShipments: ResponseResponseShipments,
    /**
     * The ResponseWarnings model constructor.
     * @property {module:model/ResponseWarnings}
     */
    ResponseWarnings: ResponseWarnings,
    /**
     * The Shipments model constructor.
     * @property {module:model/Shipments}
     */
    Shipments: Shipments,
    /**
     * The DefaultApi service constructor.
     * @property {module:api/DefaultApi}
     */
    DefaultApi: DefaultApi
  };

  return exports;
}));
